spring:
  application:
    name: config
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config/{application}
        git:
          uri: https://github.com/happy3ing/cloud.git
          username: 1049909110@qq.com
          password: mengying0308!@#
          clone-on-start: true
          search-paths: /config/{application}/
#          search-paths: '/config/common'
server:
  port: 9005
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/