spring:
  application:
    name: feign
server:
  port: 8999

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/

#熔断
feign:
  hystrix:
    enabled: true

